 spring:
 
   
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: update
    
  h2:
    console:
      enabled: true
           
  mvc:
    view:
      prefix: /views/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mujeeb@0105
    url: jdbc:mysql://localhost:3306/product 
    username: root

      